@startuml BusinessUsecase
title HomeStay Dorm Business Use Case Diagram
skinparam packageStyle rectangle

' Direction
left to right direction

' Define B.Actors
actor/ "Khách hàng" as customer

rectangle "Hệ thống Homestay Dorm" {
	rectangle "Quy trình đăng ký thuê phòng" {
		usecase/ "UC1: Đăng ký thuê phòng" as UC_DangKyThuePhong
		usecase/ "UC2: Xác định và chọn phòng" as UC_XacDinhVaChonPhong
		usecase/ "UC3: Xem phòng" as UC_XemPhong

		' Use Case Relationships
		UC_DangKyThuePhong ..> UC_XacDinhVaChonPhong : <<include>>
		UC_DangKyThuePhong <.. UC_XemPhong : <<extend>>
	}

	rectangle "Quy trình thuê phòng" {
		usecase/ "UC4: Xác nhận thuê" as UC_XacNhanThue
		usecase/ "UC5: Kiểm tra điều kiện thuê" as UC_KiemTraDieuKienThue
		usecase/ "UC6: Thực hiện đặt cọc" as UC_ThucHienDatCoc

		' Use Case Relationships
		UC_XacNhanThue ..> UC_KiemTraDieuKienThue : <<include>>
		UC_XacNhanThue ..> UC_ThucHienDatCoc : <<include>>
	}

	rectangle "Quy trình nhận phòng, ký thoả thuận thuê và bàn giao phòng" {
		usecase/ "UC7: Xử lý nhận phòng" as UC_XuLyNhanPhong
		usecase/ "UC8: Lập hợp đồng" as UC_KyHopDong
		usecase/ "UC9: Bàn giao phòng" as UC_BanGiaoPhong

		' Use Case Relationships
		UC_XuLyNhanPhong ..> UC_KyHopDong : <<include>>
		UC_XuLyNhanPhong ..> UC_BanGiaoPhong : <<include>>
	}

	rectangle "Quy trình trả phòng và hoàn cọc" {
		usecase/ "UC10: Yêu cầu trả phòng" as UC_YeuCauTraPhong
		usecase/ "UC11: Tính khoản hoàn cọc và khấu trừ" as UC_TinhHoanCocKhauTru
		usecase/ "UC12: Thanh lý hợp đồng" as UC_ThanhLyHopDong

		' Use Case Relationships
		UC_YeuCauTraPhong ..> UC_TinhHoanCocKhauTru : <<include>>
		UC_YeuCauTraPhong ..> UC_ThanhLyHopDong : <<include>>
	}
}


' Actor - Main Use Cases Associations
customer -- UC_DangKyThuePhong
customer -- UC_XacNhanThue
customer -- UC_XuLyNhanPhong
customer -- UC_YeuCauTraPhong

@enduml
