@startuml HomeStay Dorm
title HomeStay Dorm Business Use Case Diagram
skinparam packageStyle rectangle

' Direction
left to right direction

' Define B.Actors
actor/ "Khách hàng" as customer


rectangle "Quy trình đăng ký thuê phòng" {
	usecase/ "Đăng ký thuê phòng" as UC_DangKyThuePhong
	usecase/ "Xác định và chọn phòng" as UC_XacDinhVaChonPhong
	usecase/ "Xem phòng" as UC_XemPhong

	' Use Case Relationships
	UC_DangKyThuePhong ..> UC_XacDinhVaChonPhong : <<include>>
	UC_XemPhong ..> UC_DangKyThuePhong : <<extend>>
}

' Actor - Main Use Cases Associations
customer --> UC_DangKyThuePhong

@enduml
