@startuml Business Use Case HomeStay Dorm
title Business Use Case: Quản lý Ký túc xá HomeStay Dorm

left to right direction

' Định nghĩa Actor
actor "Khách hàng" as user

' Định nghĩa các Use Case chính và phụ
usecase "Đăng ký thuê phòng" as UC_DangKy
usecase "Xác định và chọn phòng" as UC_ChonPhong
usecase "Xem phòng" as UC_XemPhong

usecase "Xác nhận thuê" as UC_XacNhan
usecase "Kiểm tra điều kiện thuê" as UC_KiemTraDK
usecase "Thực hiện đặt cọc" as UC_DatCoc

usecase "Xử lý nhận phòng" as UC_NhanPhong
usecase "Lập hợp đồng" as UC_LapHopDong
usecase "Bàn giao phòng" as UC_BanGiao

usecase "Trả phòng" as UC_TraPhong
usecase "Tính khoản hoàn cọc\nvà khấu trừ" as UC_TinhTien
usecase "Thanh lý hợp đồng" as UC_ThanhLy

' Định nghĩa các mối quan hệ (Relationships)

' 1. Nhóm Đăng ký thuê phòng
user -- UC_DangKy
UC_DangKy ..> UC_ChonPhong : <<include>>
UC_XemPhong ..> UC_DangKy : <<extend>>

' 2. Nhóm Xác nhận thuê
user -- UC_XacNhan
UC_XacNhan ..> UC_KiemTraDK : <<include>>
UC_XacNhan ..> UC_DatCoc : <<include>>

' 3. Nhóm Xử lý nhận phòng
user -- UC_NhanPhong
UC_NhanPhong ..> UC_LapHopDong : <<include>>
UC_NhanPhong ..> UC_BanGiao : <<include>>

' 4. Nhóm Trả phòng
user -- UC_TraPhong
UC_TraPhong ..> UC_TinhTien : <<include>>
UC_TraPhong ..> UC_ThanhLy : <<include>>

@enduml