@startuml ThanhToan_ClassDiagram
skinparam classAttributeIconSize 0
skinparam style strictuml
title Class Diagram - UC16: Thanh toán

class "ScreenPayment" <<boundary>> {
    + selectMethod()
    + showQRCode()
    + notifyResult()
}

class "Payment" <<control>> {
    - invoiceId: String
    - contractId: String
    - method: String
    - amount: Double
    - paymentDate: Date
    - signDate: Date
    - status: String
    + <<static>> createPaymentCode(method)
    + <<static>> verifyTransaction()
    + <<static>> updateRoomStatus()
}

class "PaymentDB" <<entity>> {
    + saveInvoice()
}
class "ContractDB" <<entity>> {
    + create()
}

"ScreenPayment" ..> "Payment"
"Payment" ..> "PaymentDB"
"Payment" ..> "ContractDB"

@enduml