@startuml SystemUsecase
title Đăng ký thuê phòng - Use Case Diagram

skinparam packageStyle rectangle

' Direction
left to right direction

' Define S.Actors
actor "Khách hàng" as customer #Lime
actor "Nhân viên quản lý chi nhánh" as manager #DarkOrange
actor "Nhân viên sale" as sale #DeepSkyBlue
actor "Admin" as admin #Crimson


rectangle "Màn hình chung"{
    usecase "Đăng nhập" as UC_DangNhap
    usecase "Đăng xuất" as UC_DangXuat
    usecase "Quản lý tài khoản" as UC_QuanLyTaiKhoan

    UC_DangXuat ..> UC_DangNhap : <<extend>>
    UC_QuanLyTaiKhoan ..> UC_DangNhap : <<extend>>
}

rectangle "Màn hình khách hàng"{
    usecase "Đăng ký tài khoản" as UC_DangKyTaiKhoan

    usecase "Đăng ký thuê phòng" as UC_DangKyThuePhong
    usecase "Lựa chọn phòng" as UC_LuaChonPhong
    usecase "Đăng ký xem phòng" as UC_DangKyXemPhong
    

    customer -- UC_DangKyTaiKhoan

    UC_DangKyThuePhong ..> UC_DangNhap : <<extend>>
    UC_DangKyThuePhong ..> UC_LuaChonPhong : <<include>>
    UC_DangKyXemPhong ..> UC_DangKyThuePhong : <<extend>>
}

rectangle "Màn hình nhân viên quản lý chi nhánh"{
    usecase "Quản lý phòng" as UC_QuanLyPhong
    usecase "Quản lý khách thuê" as UC_QuanLyKhachHang
    usecase "Quản lý hợp đồng thuê phòng" as UC_QuanLyHopDongThuePhong

    UC_QuanLyPhong ..> UC_DangNhap : <<extend>>
    UC_QuanLyKhachHang ..> UC_DangNhap : <<extend>>
    UC_QuanLyHopDongThuePhong ..> UC_DangNhap : <<extend>>
}

rectangle "Màn hình nhân viên sale"{
    usecase "Quản lý lịch xem phòng" as UC_QuanLyLichXemPhong

    UC_QuanLyLichXemPhong ..> UC_DangNhap : <<extend>>
}

rectangle "Màn hình Admin"{
    usecase "Quản lý ký túc xá" as UC_QuanLyKyTucXa
    usecase "Quản lý nhân viên" as UC_QuanLyNhanVien
    usecase "Tạo tài khoản nhân viên" as UC_TaoTaiKhoanNhanVien

    UC_QuanLyKyTucXa ..> UC_DangNhap : <<extend>>
    UC_QuanLyNhanVien ..> UC_DangNhap : <<extend>>
    UC_TaoTaiKhoanNhanVien ..> UC_QuanLyNhanVien : <<extend>>
}

' Actor - Main Use Cases Associations
customer -- UC_DangNhap
manager -- UC_DangNhap
sale -- UC_DangNhap
admin -- UC_DangNhap


@enduml
