@startuml YeuCauTraPhongUsecase
title Yêu Cầu Trả Phòng
skinparam packageStyle rectangle

left to right direction

actor "Khách hàng" as customer
actor "Nhân viên" as employee

rectangle "Màn hình chung" {
  usecase "Đăng nhập" as UC_DangNhap
}

rectangle "Màn hình của khách hàng" {
  usecase "Yêu cầu trả phòng" as UC_YeuCauTraPhong
}

rectangle "Màn hình của nhân viên" {
  usecase "Quản lý yêu cầu trả phòng" as UC_QuanLyYeuCauTraPhong
  usecase "Tính khoản hoàn cọc và khấu trừ" as UC_TinhKhoanHoanCoc
  usecase "Thanh lý hợp đồng" as UC_ThanhLyHopDong
}

rectangle "Màn hình ADMIN quản lý" {
  usecase "Quản lý phòng" as UC_QuanLyPhong
}

' Relationships
customer -- UC_DangNhap 

employee -- UC_DangNhap

UC_QuanLyPhong ..> UC_DangNhap : <<extend>>
UC_YeuCauTraPhong ..> UC_DangNhap : <<extend>>
UC_QuanLyYeuCauTraPhong ..> UC_DangNhap : <<extend>>

UC_TinhKhoanHoanCoc ..> UC_QuanLyYeuCauTraPhong : <<extend>>
UC_ThanhLyHopDong ..> UC_QuanLyYeuCauTraPhong : <<extend>>
UC_ThanhLyHopDong ..> UC_QuanLyPhong : <<include>>

@enduml
