@startuml DangXuat_ClassDiagram
title Class Diagram - UC13: Đăng xuất

' --- STYLE CONFIGURATION ---
skinparam {
    ClassBackgroundColor White
    ClassBorderColor #2D3E50
    ArrowColor #2D3E50
    DefaultFontName "Arial"
    DefaultFontSize 24
    Padding 5
}

' --- BOUNDARY LAYER ---
class "Header" as Header <<boundary>> {
    + btnLogout: Button
    + handleLogout(): void
}

@enduml
