@startuml DangXuat_SequenceDiagram
title Sequence Diagram - UC13: Đăng xuất

' --- STYLE CONFIGURATION ---
skinparam {
    BackgroundColor White
    ArrowColor #2D3E50
    DefaultFontName "Arial"
    DefaultFontSize 24
    ParticipantPadding 20
    BoxPadding 10
}

actor "Khách hàng / Nhân viên" as Actor
boundary "ScreenHome" as GUI <<boundary>>
control "User" as BUS <<control>>
database "UserDB" as DB <<database>>

autonumber

Actor -> GUI: Click "Đăng xuất"
GUI -> BUS: logout()
BUS -> DB: clearSession()
DB --> BUS: Hoàn tất
BUS --> GUI: Thành công
GUI --> Actor: Đăng xuất thành công
GUI -> GUI: Chuyển hướng đến trang Đăng nhập

@enduml
