@startuml
actor "Khách hàng" as KhachHang
boundary ": CheckoutRequestScreen" as Screen
entity ": Contract" as Contract
entity ": CheckoutRequest" as Request
database ": CheckoutRequestDB" as RequestDB
database ": ContractDB" as ContractDB

KhachHang -> Screen: 1: Show()
activate Screen
Screen -> Contract: 2: GetActiveContractByCustomer()
activate Contract
Contract -> ContractDB: 3: GetActiveContractByCustomer()
activate ContractDB
deactivate ContractDB
deactivate Contract
deactivate Screen

KhachHang -> Screen: 4: Chọn phòng/giường cần trả
activate Screen
deactivate Screen

KhachHang -> Screen: 5: Nhập thông tin và tải giấy tờ
activate Screen
deactivate Screen

KhachHang -> Screen: 6: btnSubmit_Click()
activate Screen

alt Điền đầy đủ thông tin
    Screen -> Request: 7: CreateRequest()
    activate Request
    deactivate Screen
    Request -> RequestDB: 8: Insert()
    activate RequestDB
    deactivate RequestDB
    deactivate Request
end

alt  Đã tạo yêu cầu trả phòng
    KhachHang -> Screen: 9: btnSubmit_Cancel()
    activate Screen
    Screen -> Request: 10: CancelRequest()
    activate Request
    deactivate Screen
    Request -> RequestDB: 11: RemoveById()
    activate RequestDB
    deactivate RequestDB
    deactivate Request
end
@enduml
