@startuml
title Subprocess: Thực hiện đặt cọc

|#WhiteSmoke|Nhân viên Sale|
|#LavenderBlush|Kế toán|
|#AliceBlue|Quản lý|
|#HoneyDew|Khách hàng|

start

|Nhân viên Sale|
:Chuyển thông tin cho Kế toán tính tiền cọc;

|Kế toán|
:Tính toán số tiền cọc;
:Trả kết quả cho Sale;

|Nhân viên Sale|
:Gửi yêu cầu thanh toán + thông báo mức cọc;
:Hướng dẫn thông tin thanh toán;

|Khách hàng|
:Thực hiện thanh toán;

|Nhân viên Sale|
:Chờ minh chứng thanh toán (≤24h);

if (Có người khác đặt cọc thành công?) then (Có)

#Pink:Thông báo huỷ yêu cầu đặt cọc;
stop

else (Không)
endif

|Nhân viên Sale|

if (Nhận thanh toán hợp lệ trong 24h?) then (Không)

#Pink:Thông báo huỷ yêu cầu đặt cọc;
stop

else (Có)

:Gửi minh chứng cho Quản lý;

endif

|Quản lý|
:Đối chiếu thông tin giao dịch & xác nhận hợp lệ;
note right
    thông tin giao dịch (đọc)
    phòng (ghi)
    giường (ghi)
    trạng thái (ghi)
end note

|Nhân viên Sale|
:Thông báo đặt cọc thành công;
:Thông báo thời hạn lập hợp đồng;

stop
@enduml